spring.application.name=order-service
server.port=8081
server.error.include-message=ALWAYS
# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=example
spring.jpa.hibernate.ddl-auto=none
inventory.url=http://localhost:8082
# Documentation
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
# Actuator configuration
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS
# Resilience4j configuration
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.waitDurationInOpenState=5000
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
# Resilience4j timeout configuration - quá 2 giây sẽ bị coi là lỗi timeout
resilience4j.timelimiter.instances.inventoryServiceCircuitBreaker.timeoutDuration=2000
# Resilience4j retry configuration
# Gateway sẽ tự retry tối đa 3 lần, mỗi lần cách nhau 2 giây, nếu request bị lỗi và route có gắn retry
resilience4j.retry.instances.inventoryServiceCircuitBreaker.maxAttempts=3
resilience4j.retry.instances.inventoryServiceCircuitBreaker.waitDuration=2000
# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=order-placed
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.registry.url=http://localhost:8089
